import pygame
#import sys

# Game constants

# Misc constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BG_IMG_PATH = "assets/bg.png"
SCREEN_BACKGROUND_COLOR = "black"
TEXT_UI_PRIMARY_COLOR = (255, 255, 255)
MENU_H1_COLOR = '#b68f40'
UI_FONT = 'RuneScape UF'
UI_FONT_SIZE = 40
UI_INPUT_WIDTH = 400
UI_INPUT_X = 50
UI_INPUT_Y = 50
MENU_BG_COLOR = (0, 0, 0)
DIGITAL_TIMER = 60
BUTTON_BASE_COLOR = "#d7fcd4"
BUTTON_HOVERING_COLOR = (255, 255 ,255)
OPTIONS_BG_COLOR = "black"

# Player constants
PLAYER_HP = 5
PLAYER_WIDTH = 0
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.11
PLAYER_DMG_COOLDOWN = 1.2
PLAYER_SHOT_COLOR  = "white"
PLAYER_SHOT_WIDTH = 0
PLAYER_DMG_COLOR = "red"
PLAYER_DMG_COOLDOWN_COLOR = "grey"
PLAYER_COLOR = "white"

# Asteroid constants
ASTEROID_WIDTH = 2
ASTEROID_ACCEL = 1.0002
ASTEROID_DMG = 1
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_SHOT_COOLDOWN = 0.8
ASTEROID_SPLIT_VELOCITY_MULTIPLIER = 1.2
ASTEROID_MIN_SPLIT_ANGLE = 20
ASTEROID_MAX_SPLIT_ANGLE = 50
ASTEROID_MAX_SPAWN_ANGLE = 30
ASTEROID_MIN_SPAWN_ANGLE = -30
ASTEROID_COLOR = "red"

# Elite constants
IS_ELITE = False
ELITE_HP_MULTIPLIER = 1.3
ELITE_DMG_MULTIPLIER = 10

# Boss constants
RARE_RADIUS = 80
LIEUTENANT_HP = 25
LIEUTENANT_RADIUS = 100
MINI_BOSS_HP = 50
MINI_BOSS_RADIUS = 120
BOSS_HP = 100
BOSS_RADIUS = 160

# Weapom constants
SHOT_RADIUS = 5
